import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Link from "next/link";

function Home({ user }) {
  return (
    <div className="flex justify-center mt-80">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h3>Hello, {user.name}</h3>
        <Link href="/api/auth/logout">Logout</Link>
      </div>
    </div>
  );
}

export default Home;

export const getServerSideProps = withPageAuthRequired();
